### ISSUE TITLE
Komma gegen Punkt austauschen.

### ISSUE THREAD

**Issue by Dreistein19** [jolichter/ioBroker_dwdWeather#1]
Vielen Dank für das Script.
Sicher ist es es mein Fehler.
Aber, die Temperaturen werden mit Komma als Trenner gespeichert.
Leider werden die Daten so nicht in der influxdb gespeichert. Diese erwartet scheinbar einen Punkt.
(3,14 = 3.14)

Gibt es die möglichkeit dieses in deinem Script, als Noob, zu ändern ?

MfG

**Comment by jolichter** [comment]
Hi, wenn du ioBroker in Verbindung mit InfluxDB betreibst, ist es richtig, dass, ähnlich wie bei vielen anderen DB-Systemen, ein Punkt (.) als Standard-Dezimaltrennzeichen verwendet wird. In der Tat sollte das auch für die Standard DB von ioBroker gelten.

Das Speichern von Zahlen mit einem Komma anstatt einem Punkt resultiert vermutlich aus der Art und Weise, wie Zahlenwerte aus CSV-Dateien gelesen und anschließend als Strings behandelt werden. Um dieses Problem zu beheben, habe ich eine Funktion hinzugefügt. Diese Lösung funktioniert nur, solange sichergestellt ist, dass Kommas ausschließlich als Dezimaltrennzeichen in den Zahlenwerten fungieren, nicht jedoch als Tausendertrennzeichen. In meinen Test hat diese Lösung funktioniert.

Du kannst diesen Ansatz auch in deinem Setup mit InfluxDB auszuprobieren. Ich würde mich über eine Rückmeldung von dir freuen.

**Comment by Dreistein19** [comment]
Bisher keine Probleme.
Danke sehr.
Nur eine Bitte, den Link zu dieser Seite bitte im Source Code vermerken.
Ich vergessen immer wo ich dein Script her habe. Vermutlich war es ein Eintrag in ioBroker Forum.
MfG

**Comment by jolichter** [comment]
OK, Danke für deine Rückmeldung
